### ISSUE TITLE
problem occurring in coregistering dems

### ISSUE THREAD

**Issue by Nauman95** [dshean/demcoreg#24]
dear sir I am trying to co register SRTM dem and TanDEM-X dem for all indus basin of high mountain asia. I am using WSL Ubuntu terminal on windows 10. when I process the code it ends in crashing my system.  the attached image is taken just before it crashes the system and restarts it. kindly help me how can I deal with this problem. 
![IMG_20200829_032411](https://user-images.githubusercontent.com/63490080/91608963-163c0b00-e9a9-11ea-8994-a5a3ed4f8379.jpg)

**Comment by dshean** [comment]
Hi @Nauman95. Hard to diagnose without seeing error messages, and running this should not restart your system.
Those are really large input DEMs - each has 314M float32 values, which will occupy 1.26 GB of RAM.  Loading them into memory and storing results of subsequent calculations (each additional grid occupies another 1.26 GB) is likely filling your RAM.  I recommend you reduce the input DEM size/resolution or try running on a computer with more RAM if that is an option.
Also, there should be limited translation offset between SRTM and TDX for such a large area (assuming both products use consistent projection/datum).  But there will be local offsets, likely 10s of meters over smaller features, and these are not uniform across the full DEM area you're considering.  So if you crop to a smaller area, you will get better alignment for features of interest.  Hopefully that helps.

**Comment by Nauman95** [comment]
Dear Shean sir, on your suggestion I reduced the resolution and also selected the area where glaciers are preasent (upper indus basin). This worked and i got the results. Thank you for your kind guidance.
