### ISSUE TITLE
Two different reference surfaces

### ISSUE THREAD

**Issue by tobkug** [dshean/demcoreg#27]
Hi

I want to co-register two different digital elevation models

1):  Lidar dem (vertical datum: geoid EGM96)
2):  stereoscopic Pléiades dem (vertical datum: ellipsoid WGS84)
 
Do i have to apply a vertical datum transformation first before using `dem_align.py`?

**Comment by ShashankBice** [comment]
It would be best to indeed convert the Lidar DEM to ellipsoidal height for best results. If the geoid undulation in your study area is uniform, then geoid to ellipsoid height difference will be pretty much constant and dem_align.py can recover that z offset during co-registration, even if you don't convert the reference datums. But there can be subtle artifacts, for which I would say having the datasets vertical datum to be consistent is the best bet. You can use the latest gdal3 datum conversion recipe or the Ames stereo pipeline dem_geoid tool to convert between geoid to ellipsoidal heights.

**Comment by tobkug** [comment]
thank you
