### ISSUE TITLE
beginners-doc

### ISSUE THREAD

**Issue by deollamas** [dshean/demcoreg#32]
Hi I followed the beginners-doc.

I keep having this error whenever I ran dem_align.py -h 
![Screen Shot 2021-07-28 at 11 39 50 PM](https://user-images.githubusercontent.com/86864982/127352667-2d79275e-a568-4958-96c5-fb8aba547e98.png)

**Comment by dshean** [comment]
Hi @deollamas.  Looks like you don't have `pygeotools` installed in your `demcoreg_env` environment - maybe try repeating steps 5 and 6: https://github.com/dshean/demcoreg/blob/master/docs/beginners_doc.md#installation
