### ISSUE TITLE
Error -38

### ISSUE THREAD

**Issue by morgan-mcdonnell** [dshean/demcoreg#35]
I run the dem_align.py command successfully and get an output dem after four iterations. However, the following error message pops immediately after I run the dem_align.py command. It appears three times in succession. Wondering what is causing this error message, and if it will cause any problems? Both of my input dems are in a projected coordinate system. Thanks!

proj_create: Error -38: failed to load datum shift file

**Comment by dshean** [comment]
Can you please provide the full output (copy/paste from terminal, with context around the error message)?
What is CRS of the two input datasets (from `gdalinfo`)?
My guess is that they have different CRS that requires a datum shift grid.  This is independent of demcoreg - these must be manually downloaded to your PROJ share directory.  See documentation on the PROJ website - there is a convenient utility called `projsync` that will do this automatically.  If you can provide more details on your environment (e.g., GDAL version, PROJ version), that would also be useful.

**Comment by morgan-mcdonnell** [comment]
Sure! I'm attaching the output. Both DEMs have this CRS: EPSG:32718 - WGS 84 / UTM zone 18S - Projected.
[demcoreg_output.docx](https://github.com/dshean/demcoreg/files/7498168/demcoreg_output.docx)

**Comment by dshean** [comment]
OK.  Those errors don't seem to be an issue, and dem_align.py converges with reasonable offset values.  I think you can safely ignore if the output looks good.

My guess is that some of those errors are related to projections initiated in pygeotools/lib/geolib.py using older PROJ4 syntax.  Some of that code needs to be overhauled/updated for latest GDAL/PROJ.

**Comment by morgan-mcdonnell** [comment]
Great, thanks for looking into it!
