### ISSUE TITLE
I can't find a program that generates "dem_align_stats.pkl".

### ISSUE THREAD

**Issue by js3497** [dshean/demcoreg#42]
Hello!
For the "dem_align_post.ipynb".I wonder how should I get "dem_align_stats.pkl". I could only find the program to generate "dem_align_stats_201909_rerun.pkl".

**Comment by dshean** [comment]
Hi @js3497 .  Sorry about the delayed response - this slipped through the cracks.  I believe some of the filenames were hardcoded (or later renamed) for multiple runs of that notebook with different inputs.  Hopefully that makes sense.

**Comment by js3497** [comment]
Hi @dshean Can you be more specific? I really couldn't find a step that would generate "dem_align_stats.pkl".
