### ISSUE TITLE
Missing requirement: demtools/stats.py

### ISSUE THREAD

**Issue by tania80** [dshean/demcoreg#5]
Hello, I'm trying to use the dem_coreg.sh script, and the execution fails on line 94 with the error 

    /home/USER/src/demtools/stats.py: No such file or directory

I could not find in the README or documentation which ` demtools`  should be used to complete the functionality.

Thanks for any information.

**Comment by ShashankBice** [comment]
Hi!
The package (demtools) you are referring to is not public at this moment. For this particular problem, you can replace the stats.py by robust_stats.py tool, which you get when you install the demcoreg package.
Moreover, if you are coregistering 2 dems, you might also want to have a look at the newly updated "nuth and kaab" implementation in dem_align.py (https://github.com/dshean/demcoreg/blob/master/demcoreg/dem_align.py)

**Comment by dshean** [comment]
Hi @tania80 
I pushed some changes to dem_coreg.sh to use robust_stats.py to get the count of valid pixels.  As @ShashankBice suggested, the dem_align.py tool might be a good option if you are working with two gridded rasters.  If you are working with point cloud data, you will want to use pc_align.  The dem_coreg.sh script is something of a custom wrapper for my application, which uses some nontrivial masking steps.  You might also consider using ASP pc_align directly, and can consult the ASP manual for more details.  Hope that helps.
